apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-server-app
  labels:
    app: http-server-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: http-server-app
  template:
    metadata:
      labels:
        app: http-server-app
    spec:
      containers:
        - name: http-server-app
          image: http-server-app:v1.1759732761
          imagePullPolicy: Never
          # image: rreyfockandroid/http-server-app:latest  # ğŸ” podaj tu swÃ³j obraz Dockerowy
          ports:
            - containerPort: 7092
          resources:
            limits:
              cpu: "100m"
              memory: "128Mi"
